<?php $this->headTitle('Home'); ?>

<div class="row">
    <div class="col-md-12">
      <form method="POST" action="/publish">
        <h3>
            <i class="fa fa-key"></i> Publish my Key
        </h3>
        <textarea name="pgp-key" class="form-control" placeholder="Copy/Paste your PGP Key"></textarea>
        <br>
        <div class="d-flex justify-content-end">
          <input type="submit" value="Publish" class="btn btn-xs btn-primary">
        </div>
      </form>
    </div>
</div>
