<?php $this->headTitle('Received'); ?>

<div class="row">
  <div class="col-md-12">
    <h3>
      Thank you for submitting your public key.
    </h3>
    <p>
      Please check the following email addresses to approve the publish:
    </p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->users as $user): ?>
          <tr>
            <td><?php echo $user->name; ?></td>
            <td><?php echo $user->email; ?></th>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>